In [ ]:
import numpy as np
import random

In [ ]:
np.random.seed(5)
r = np.random.randint(1,21,(6,6))
print(r)

[[ 4 15 16  7 17 10]
 [ 9  5  8 17 17  8]
 [13 16 18  8 17 13]
 [14 12  2 16 19 10]
 [11 10 10  2 19  8]
 [17 15  6  1 17  5]]


In [ ]:
mean = r.mean(axis=0)
print(mean)
print()
res = r - mean
print(res)

[11.33333333 12.16666667 10.          8.5        17.66666667  9.        ]

[[-7.33333333  2.83333333  6.         -1.5        -0.66666667  1.        ]
 [-2.33333333 -7.16666667 -2.          8.5        -0.66666667 -1.        ]
 [ 1.66666667  3.83333333  8.         -0.5        -0.66666667  4.        ]
 [ 2.66666667 -0.16666667 -8.          7.5         1.33333333  1.        ]
 [-0.33333333 -2.16666667  0.         -6.5         1.33333333 -1.        ]
 [ 5.66666667  2.83333333 -4.         -7.5        -0.66666667 -4.        ]]


In [ ]:
p = res[abs(res) >= 1.5]
print(p)

[-7.33333333  2.83333333  6.         -1.5        -2.33333333 -7.16666667
 -2.          8.5         1.66666667  3.83333333  8.          4.
  2.66666667 -8.          7.5        -2.16666667 -6.5         5.66666667
  2.83333333 -4.         -7.5        -4.        ]


In [ ]:
print(np.sum(p))
print(np.mean(p))
print(np.std(p))
print(np.min(p))
print(np.max(p))

1.0
0.045454545454545456
5.365005817298902
-8.0
8.5


In [ ]:
np.random.shuffle(r)
print(r[:3])

[[17 15  6  1 17  5]
 [ 4 15 16  7 17 10]
 [13 16 18  8 17 13]]
